version: '3'
services:
    app:
      container_name: meli-product-list
      build:
        context: ../../
        dockerfile: ./conf/docker/Dockerfile
      environment:
        - NODE_ENV=production
      ports:
        - 80:3000
